
== 6. Definisjon og Alternativ formulering

*Hensikt*:

Fordi begreper er abstrakte, trenger vi definisjoner og termer for å
uttrykke dem og kommunisere om dem. En definisjon er et muntlig eller
skriftlig utsagn som beskriver meningsinnholdet og avgrenser et begrep
fra et annet. Definisjonen av et begrep i et gitt fagområdet eller
bruksområde skal si noe om kjennetegnene til begrepet.

Definisjonen er med på å forklare begrepet og avgrense det mot andre,
beslektede begreper. Relasjonen til andre begreper bidrar dermed til å
definere omfanget til et bestemt begrep..

*Anbefaling*:

Når man definerer begreper, skal man anvende kjennetegn som hver for seg
eller sammen avgrenser begrepet og skiller det fra andre, beslektede
begreper. Et tips er å la definisjonsteksten uttrykke det settet av
kjennetegn som sier noe om hva fenomenet er, istedenfor å fokusere på
hva det ikke er.

En definisjon er oppbygd av et eller flere kjennetegn, fortrinnsvis satt
sammen i én setning. Minst et av kjennetegnene bør være atskillende,
dvs. det skiller begrepet fra andre, beslektede begreper. For eksempel
inneholder definisjonen til ‘husdyr’ (se 2.2.) kjennetegnet ‘som blir
halde for nytteformål’. Dette kjennetegnet gjør at begrepet skiller seg
fra ‘kjæledyr’. I tillegg til dette atskillende kjennetegnet kan man
legge til mer informasjon i såkalte supplerende kjennetegn. Slike
supplerende kjennetegn gir ytterligere informasjon om begrepet.

Et viktig prinsipp når man skriver en definisjon er
utskiftingsprinsippet. Det innebærer at en term kan skiftes ut med
definisjonen i en løpende tekst, med mindre justeringer. For å teste
dette prinsippet kan man bytte ut termen og sette inn definisjonen.

https://www.sprakradet.no/globalassets/vi-og-vart/publikasjoner/termlosen.pdf[[.underline]#Termlosen#]
gir veiledning i skriving av definisjoner, bl.a. hvordan man bør tegne
begrepssystem for å finne atskillende kjennetegn.

Standarden krever at man til et gitt begrep kan oppgi maksimalt én (1)
definisjon per språk. Alternative formuleringer brukes til å uttrykke
definisjoner på ulike måter. Dersom de fleste begrepene i virksomheten
har sitt opphav i regelverk eller fagtekster, kan alternative
formuleringer typisk være “den folkelige forklaringen”, som kan benyttes
ut til publikum og som er tilgjengelig for en større gruppe enn
fagspesialister og jurister. Man kan også velge at den folkelige
forklaringen er den “styrende/foretrukne” definisjonen, mens
definisjonen som er hentet fra regelverket, blir merket/lagt inn som en
alternativ formulering. Dette vil kunne variere ut fra virksomhetens
forvaltningsområde og målgruppe. Betydningen i definisjonen og den
alternative formuleringen skal alltid være den samme.

Ulike virksomheter vil ha ulike behov når begrep skal defineres, også
internt i virksomheten. Selv om offentlige virksomheter skal ha fokus på
klarspråk, kan det i noen tilfeller være behov for å benytte en
definisjon som ikke er i tråd med prinsippene for klarspråk. Et eksempel
er begrep som kommer fra lovgivning. Her kan definisjonen være mest
forståelig for rettsanvendere, og ikke like forståelig eller
nødvendigvis intuitiv for allmennheten. Dette kan komme av at lovgiver
har behov for å benytte avgrensninger innenfor en snevrere kontekst
eller lovens/bestemmelsens virkeområde (f.eks. innsnevret tolkning av
adopsjonsbegrepet i folketrygdloven), eller at definisjonene er skrevet
på en annen tid (grunnloven, gammel straffelov, mv.). I de tilfeller
hvor det finnes legaldefinisjoner eller andre typer definisjoner fra
lovgivers side, bør virksomheten legge dette til grunn.

Denne versjonen av standarden spesifiserer ikke hvordan man på en
strukturert måte kan markere hva som er hhv. original eller oversettelse
av en term eller en definisjon. Det anbefales å benytte fritekstfeltet
“merknad” til dette formål.

*Eksempler:*

For begrepet ‘d-nummer’:

* Definisjon: “identifikasjonsnummer som tildeles personer med midlertidig
tilknytning til Norge, det vil si som ikke er bosatt i Norge.”

* Alternativ formulering som brukes i kommunikasjon med brukerne: “Et
d-nummer er et midlertidig identifikasjonsnummer.”


Både definisjonen og den alternative formuleringen inneholder det
atskillende kjennetegnet ‘midlertidig’, som skiller begrepet fra det
beslektede ‘fødselsnummer’.
