==Innledning
=== Bakgrunn

Digital Agenda og Digitaliseringsrundskrivet viser til målet om at brukeren ikke skal trenge å avgi informasjon som han allerede har avgitt. I https://lovdata.no/dokument/NL/lov/1997-06-06-35#shareModal[Lov om Oppgaveregisteret] § 5 stilles det krav til statlige virksomheter at informasjon fra næringslivet er samordnet slik at man ikke etterspør samme informasjon flere ganger. Det langsiktige målet er at gjenbruk er hovedregel.

Den enkelte offentlige virksomheten har etter https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2522147/[Digitaliseringsrundskrivet] (spesielt punkt 1.4 og 2.2) krav til å holde at virksomhetene skal holde en oversikt over hvilke data de forvalter. Difi forvalter et https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning[felles offentlig rammeverk for informasjonsforvaltning] som inneholder veiledere osv.. relevant for informasjonsforvaltning i offentlig sektor. En “https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/veileder-orden-i-eget-hus[Veileder for orden i eget hus]” er laget for å støtte arbeid med å etablere en praksis for dette i egen virksomhet og en https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/faglig-arena-informasjonsforvaltning[faglig arena for informasjonsforvaltning] etablert av Difi for å gi erfaringsutveksling mellom de offentlige virksomhetene.

Offentlig virksomheter forvalter store mengder opplysninger fordelt på mange registre. For at offentlige virksomheter skal utnytte informasjon fra andre ved utvikling av digitale brukerrettede tjenester, trenger de å vite hvilken informasjon som finnes og kan gjenbrukes. De behøver å kjenne til hvilke datasett som finnes, og evaluere om de er riktige til sitt formål. Til dette trengs egne oversikter å eksponeres utenfor virksomheten. Private virksomheter trenger en oversikt for å kunne finne, forstå og nyttiggjøre seg av åpne data til transparens, innovasjon og næringsutvikling, og få tilgang til opplysninger som kan bedre brukers prosess i private løsninger (myData) der der deling skjer med brukers samtykke.

En felles oversikt etableres med Felles datakatalog. DCAT-AP v1.1 er den gjeldende europeiske spesifikasjonen for beskrivelser av datasett og datakataloger. Formålet er å gjøre det enklere å søke etter åpne datasett på tvers av dataportaler i EUs medlemsstater. En norsk versjon kalt DCAT-AP-NO 1.1 er basert på den europeiske. Den norske standarden inneholder utvidelser som er nyttig for også å beskrive datasett som ikke er åpne.
