
== Anbefaling fra arbeidsgruppen

=== Sammenstilling

I arbeidet med å lage et kriteriesett (minimum) for å beskrive formål og hjemmel, må vi vite hva som er godt nok til at det er nyttig, men ikke så krevende at det avskrekker fra å dokumentere og forvalte.

Det kan være vanskelig å finne balansen mellom for lite og for mye dokumentasjon. Vi tar utgangspunkt i at beskrivelsen i datakatalogen skal være tilstrekkelig til at brukeren kan bestemme seg for om det er verdt å undersøke muligheten nærmere for gjenbruk, for eksempel ved å henvende seg til kontaktpersonen til datasettets eier som er et eget metadatafelt.

Det er trolig også hensiktsmessig at det for noen datasett legges til flere opplysninger enn for andre. Dette gjelder særlig grunndata, hvor beskrivelsene må være mer omfattende. For andre opplysninger vil neppe datakatalogen i seg selv gi tilstrekkelig dokumentasjon til at andre kan konkludere på om opplysningene kan legges til grunn i egen saksbehandling.

Tabellen under inneholder en sammenstilling av anbefalingene fra arbeidsgruppen. Hver av anbefalingene beskrives nærmere i etterfølgende avsnitt.

|===
|*Beskrivelse av ...*|*Løsningsforslag*

|Behandlingsformål|Bruk: https://doc.difi.no/dcat-ap-no/#datasett-beskrivelse[«Beskrivelse» i DCAT-AP-NO 1.1]
|Behandlingsgrunnlag|Bruk: to nye felt
|Tilgangsnivå|Bruk: https://doc.difi.no/dcat-ap-no/#datasett-tilgangsniva[«Tilgangsnivå» i DCAT-AP-NO 1.1]
|Skjermingshjemmel|Bruk: https://doc.difi.no/dcat-ap-no/#datasett-skjermingshjemmel[«Skjermingshjemmel» i DCAT-AP-NO 1.1]
|Utleveringshjemmel|Bruk: nytt felt
|===

=== Beskrivelse av behandlingsformål

==== Anbefaling

Arbeidsgruppen mener at formålet med behandlingen av opplysningene i datasettet må komme tydelig frem, fordi dette er vesentlig informasjon for ny bruker av opplysningene. Arbeidsgruppen har i særlig grad vektlagt behandlingen av personopplysninger fordi gjenbruk av borgerens opplysninger er sentralt for anvendelsen av felles datakatalog.  Vi har derfor valgt å kalle det for behandlingsformål. Det er imidlertid ikke en begrensning til kun personopplysninger, da en god beskrivelse av hva opplysningene i datasettet er brukt til også vil være viktig informasjon for å vurdere gjenbruksverdien.

Det foreslås at det ikke innføres et eget felt for formål, men at man bruker feltet https://doc.difi.no/dcat-ap-no/#datasett-beskrivelse[beskrivelse] i DCAT-AP-NO v.1.1. Feltet må være fritekst og obligatorisk (uendret ift. DCAT-AP-NO v.1.1). Dersom dette feltet fylles ut i henhold til veiledningen om bruk av DCAT fra Difi vil det gi en god forklaring på hva som var hensikten med behandlingen av opplysningene i datasettet og hva det inneholder.

Vi mener at beskrivelse av datasettet sammen med andre felter i datakatalogen til sammen gir tilstrekkelig informasjon til brukeren av felles datakatalog om hvilket formål avgiverorganet har brukt opplysningene til.

Arbeidsgruppen anbefaler at veilederen oppdateres med tekst som forklarer hvordan behandlingsformål skal beskrives.

==== Brukerbehov

Arbeidsgruppen mener det er behov for informasjon om hva som var det opprinnelige formålet med behandlingen av opplysningene i datasettet ved utredning av muligheten for gjenbruk til ny behandling. Dette vil være både i regel/tjenesteutviklingsfasen og til etterfølgende kontrollformål. Informasjon om formålet er også relevant for å ta stilling til behovet for nye hjemler for innhenting av opplysninger. Dette gjelder både for personopplysninger og andre opplysninger.

==== Feltdefinisjon

I DCAT-AP-NO 1.1 er “beskrivelse” omtalt slik:

.Datasett: beskrivelse
****
*URI*: dct:description +
*Range*: rdfs:Literal +
*Beskrivelse*: Inneholder fritekstbeskrivelse av datasettet. Kan gjentas for parallelle  språkversjoner +
*Kardinalitet*: 1..n +
*Status*: Obligatorisk +

kilde: https://doc.difi.no/dcat-ap-no/#datasett-beskrivelse
****
Arbeidsgruppen mener at vokabularet dekker behovet og at det ikke er nødvendig med en utvidelse. Dette forutsetter at det fremkommer tydelig i veilederen at formål må omfattes når datasettet skal beskrives.

Det har vært diskutert om det bør være to ulike utfyllingsfelt for beskrivelse og formål, men at det vises i samme felt i felles datakatalog. Arbeidsgruppen mener dette ikke er nødvendig fordi det i de fleste tilfeller vil være naturlig å forklare hva datasettet er brukt til når det skal beskrives. Vi antar derfor at det vil bli overlappende tekst med samme meningsinnhold, noe som kan virke forvirrende. Vi anbefaler derfor at det skal være ett utfyllingsfelt.

==== Veileder

I Difi sin veileder for beskrivelse av datasett DCAT-AP-NO versjon 1.1 er feltet “beskrivelse” omtalt slik:

.Innspill til veilederen:
Veilederen er under revidering og arbeidsgruppen anbefaler at tekst gjennomgås for å sikre at det går tydelig frem at behandlingsformål er en del av beskrivelsen. Slik teksten står nå er det kulepunktet “Hensikten med datasettet…” som er rettet mot formålsbeskrivelse.

Som omtalt under feltdefinisjon ovenfor har det vært en diskusjon om det bør være to utfyllingsfelt. Dersom det blir to felt som skal fylles ut, en for beskrivelse og en for formål, men med felles visning er det risiko for at det blir likelydende tekst i disse to feltene. Arbeidsgruppen anbefaler ikke en slik løsning. Dersom denne løsningen likevel blir valgt må kulepunktet _hensikten med datasettet_ omtales i et eget punkt i veilederen knyttet til utfyllingsfelt for behandlingsformål.

=== Beskrivelse av behandlingsgrunnlag for opplysninger, herunder personopplysninger

==== Anbefaling

.Ved behandling av personopplysninger:
Etter personopplysningsloven § 8 og 9 skal det foreligge et grunnlag for behandling av personopplysninger. Arbeidsgruppen anbefaler at det tas i bruk et eget felt for behandlingsgrunnlag med tre valgmuligheter tilsvarende inndelingen i personopplysningsloven. Det er lovhjemmel, samtykke eller nødvendighetsvurdering. Feltet er anbefalt og må fylles ut hvis datasettet inneholder personopplysninger For hver av de tre bør det også knyttes en henvisning til lov. Det bør være mulig å henvise til flere behandlingsgrunnlag fordi et datasett kan inneholde opplysninger som har ulike hjemler for behandlingsgrunnlag. Dette kan for eksempel være lovgrunnlag og samtykke eller nødvendighetsvurdering.

Det anbefales ikke å ha et eget felt for verbal beskrivelse av behandlingsgrunnlaget. Dersom dette er et behov vil det være mulig å omtale dette under feltet “beskrivelse” eller andre steder der det er fritekst. Begrunnelsen er at fritekstfelter ikke er hensiktsmessig fordi det ikke blir maskinlesbart.

==== Brukerbehovet

Dersom et datasett inneholder personopplysninger skal det være et grunnlag for behandlingen. Å få kunnskap om type behandlingsgrunnlag har stor informasjonsverdi for å vurdere om datasettet er relevant å undersøke nærmere. I tillegg gir det direkte eller indirekte informasjon om formålet med behandlingen, hvilken type utøvelse av offentlig myndighet det er og kvaliteten på dataene. At det henvises til lovgrunnlaget for samtykke eller nødvendighetsgrunn har også stor informasjonsverdi for brukeren av felles datakatalog bl.a for vurderingen av eget behov for hjemler for bruk av samme data.

Samtidig vil dette på lengre sikt gi en oversikt over det offentliges behandlingsgrunnlag som videre kan ha verdi ved endring eller utarbeidelse av nytt lovverk.

==== Eksempler

.Historie 1: Automatisert datafangst - Regelutvikling/tjenesteutvikling

Regjeringen la frem et forslag i RNB 2017 å utvide utdanningsstøtteordningen med en ny ettergivelsestype der studenter som tar lærerutdanning for trinn 1-7 og jobber som lærer i Nord-Norge etterpå, vil få ettergitt rundt 160 000 kroner. Denne ordningen trer ikke i kraft før om fem år.

Det er også fremmet et strakstiltak for Finnmark og sju kommuner i Nord-Troms der kvalifiserte grunnskolelærere får slette 20 000 kroner i studielån hvert år de arbeider i en skole i regionen. Ordningen skal vare frem til 2020.

Som tjenesteutvikler i Lånekassen trenger vi å vite om noen andre offentlige etater har register over ansatte grunnskolelærere i visse kommuner i Nord-Norge for å vurdere om vi kan bruke opplysningene i registeret til automatisk datafangst for å dokumentere at vilkårene for ettergivelse av utdanningslån er tilstede.

Ved søk i felles datakatalog må vi få en del opplysninger for å bestemme om vi bør sjekke det ut nærmere. Vi må få en god beskrivelse av hva datasettet inneholder, hvorfor dataene blir innsamlet og om det rettslige grunnlaget etaten har for å etablere registeret, om de som leverte data til registeret er primærkilden, om de har  rapporteringsplikt, for hvilken periode dataene gjelder for, hvor hyppig data blir levert, om dataene oppdateres, oppdateringsfrekvens, blir dataene rettet hvis det har vært rapportert inn feil, er det merket om dataene er endret, kan dataene utleveres uten at vi har innhentingshjemmel.

|===
|*Behov*|*JA/NEI*

|Formål/beskrivelse |Ja
|Behandlingsgrunnlag|Ja
|Utleveringshjemmel|Ja
|Tilgangsrettighet  |Ja
|Skjermingshjemmel|Ja
|Offentlig myndighetsutøvelse|Ja
|===

.Datasett fra SPK
Alle arbeidsgivere med pensjonsordning i Statens pensjonskasse (SPK) må hver måned rapportere inn opplysninger om alle sine ansatte til SPK. Opplysninger som må gis er bl.a. lønn, stillingsandel, permisjon og tittel. I tillegg til statlige etater og enkelte private virksomheter har også kommunale lærere pensjonsordning i SPK.

Det er bl.a. foreslått nye regler om ettergivelse av studielån for nærmere angitte lærere i Nord-Norge. Spørsmålet er om aktuelle lærere selv må søke om ettergivelse av studielån og dokumentere stillingsforholdet. Alternativt at lærerne får beskjed fra Lånekassen om at de kan søke, men at Lånekassen innhenter nødvendig dokumentasjon. Atter alternativt at Lånekassen ettergir studielånet automatisk. I de to siste tilfellene må arbeidsgiverne rapportere inn stillingsforholdet til Lånekassen. Spørsmålet er om Lånekassen kan gjenbruke de opplysningene arbeidsgiverne alt gir til SPK.

Ved at datasettet til SPK inneholder en beskrivelse av behandlingsgrunnlaget med henvisning til lov vil Lånekassens utvikler ved oppslag i loven forstå at datasettet kan være relevant fordi også andre enn offentlige tjenestemenn kan være medlemmer av Statens pensjonskasse.  Videre vil vi kunne se at det er pliktig medlemskap, at det er rapporteringsplikt mv.

|===
|*Tittel (datasett)*|*Beskrivelse og  behandlings-*|*Behandlings-*|*Utleverings-*|*Tilgangsnivå*|*Skjermings- hjemmel*

|Pensjon|Treffe vedtak om tjenestepensjon til i hovedsak statsansatte og (kommunale) lærere|https://lovdata.no/dokument/NL/lov/1949-07-28-26/KAPITTEL_1#§1[https://lovdata.no/dokument/NL/lov/1949-07-28-26/KAPITTEL_1#§1]|https://lovdata.no/dokument/NL/lov/1957-07-06-26/KAPITTEL_8#§27[https://lovdata.no/dokument/NL/lov/1957-07-06-26/KAPITTEL_8#§27]|Begrenset|https://lovdata.no/lov/1967-02-10/§13[https://lovdata.no/lov/1967-02-10/§13]
|===

.Andre datasett
Ved søk i felles datakatalog vil vi få treff også på andre datasett som f.eks A-ordningen. Ved god informasjon om formålet med bruk av opplysningene i datasettet, henvisning til behandlingsgrunnlaget i A-opplysningsloven vil vi raskt kunne ta stilling til om vi skal undersøke om dette datasettet er brukbart til vårt behov.

==== Feltdefinisjon

Det vil være behov for et tillegg i den norske versjonen av DCAT med ett felt med tre alternative verdier som også kan kombineres (flervalg) som fylles ut med henvisning til det rettslige grunnlaget for behandlingen av personopplysninger.

Arbeidsgruppen foreslår at feltet _behandlingsgrunnlag _omtales slik i vokabularet:

Grunnlaget for behandling av personopplysninger.

Begrepet er ikke definert i personopplysningsloven eller i GDPR. I omtalen til Datatilsynet om begrepet behandlingsgrunnlag og GDPR brukes beskrivelsen ovenfor.   (https://www.datatilsynet.no/Regelverk/EUs-personvernforordning/hva-betyr/alle-ma-kunne-oppfylle-borgernes-nye-rettigheter/[https://www.datatilsynet.no/Regelverk/EUs-personvernforordning/hva-betyr/alle-ma-kunne-oppfylle-borgernes-nye-rettigheter/])

Arbeidsgruppen foreslår i utgangspunktet at feltet _behandlingsgrunnlag_ skal ha tre verdier som vi foreslår omtales i den norske DCAT. Dersom et datasett har flere behandlingsgrunnlag vil det være behov for mulighet til å fylle ut flere verdier samtidig på et datasett.

Forslaget må harmoniseres med definisjoner i ny personopplysningslov og med den norske oversettelsen av personvernforordningen når disse foreligger.

.Forslag til verdibeskrivelse:

*Lovgrunnlag:* En henvisning til det rettslige grunnlaget for behandlingen av personopplysninger

*Samtykke:* En frivillig, uttrykkelig og informert erklæring fra den registrerte om at han eller hun godtar behandling av opplysninger om seg selv.

*Nødvendighetsgrunn:* Behandling av personopplysninger er nødvendig for de grunner som er definert i personopplysningsloven § 8 bokstav a-f eller § 9 bokstav a-h.

==== Veileder

Feltet behandlingsgrunnlag med de tre verdiene; lovgrunnlag, samtykke og nødvendighetsgrunn må forklares nærmere i veilederen slik at de som skal legge inn opplysninger om datasettet får god informasjon om hvordan feltet skal fylles ut.

Teksten i veilederen må harmoniseres med ny personopplysningslov og den norske oversettelsen av personvernforordningen når disse vedtas med ikrafttredelse i mai 2018 og det bør være en klar henvisning til dette regelverket i veilederen.

=== Beskrivelse av tilgangsnivå

==== Anbefaling

Arbeidsgruppen mener det er viktig å ha et felt som gir informasjon om hvorvidt datasettet inneholder opplysninger som er ikke-offentlig (skjermet) og ikke kan utleveres uten at mottaker har et hjemmelsgrunnlag for å motta opplysningene. Om dataene er begrenset eller ikke-offentlig gir viktig informasjon for den som skal vurdere om datasettet er egnet til sitt bruk.

Arbeidsgruppen anbefaler å benytte feltet https://doc.difi.no/dcat-ap-no/#datasett-tilgangsniva[datasett: tilgangsnivå] i DCAT-AP-NO v.1.1, som angir hvilket tilgangsnivå datasettet har via en nedtrekksmeny med tre valg, jf. EU-definisjonen.

Se <<beskrivelse-skjermingshjemmel>> for arbeidsgruppens forslag til å angi informasjon om betaling.

==== Brukerbehovet

Det er behov for å angi i hvilken grad datasettet kan bli gjort tilgjengelig for allmennheten, uten hensyn til om det er publisert eller ikke. Det er nødvendig å angi om datasettet er helt eller delvis skjermet for innsyn.

Det er også et behov for informasjon om bruk av datasettet medfører kostnader eller andre forhold som krever finansiering.

Det er behov for tydelige avgrensninger slik at det blir enkelt å fylle ut feltene. Dette er en informasjonsutfordring som anbefales løst i veilederen.

==== Eksempler

NAV ønsker å forenkle, effektivisere og heve kvaliteten på tjenesten arbeidsrettet oppfølging. Brukere som trenger bistand for å komme seg i arbeid skal gi en beskrivelse av egen situasjon i en digitalisert løsning. For å forenkle informasjonsinnhentingen, både for bruker og NAV, kan et alternativ være at NAV presenterer overfor bruker relevante opplysninger som allerede er registrert hos NAV og innhenter annen relevant informasjon fra andre offentlige virksomheter. Det kan for eksempel være opplysninger om hvorvidt utenlandsk utdanning er godkjent i Norge fra Nokut, om gjennomført introduksjonsprogram fra NIR, IMDI og om godkjent oppholdstillatelse i Norge fra UDI. For å vurdere om disse opplysningene lovlig kan gjenbrukes til formålet arbeidsrettet oppfølging, så trenger NAV å vite om disse opplysningenes behandlingsgrunnlag, formål og om de er underlagt lovpålagt taushetsplikt.

==== Feltdefinisjon

Arbeidsgruppen mener at DCAT-AP-NO 1.1 “tilgangsnivå” vil dekke brukerbehovet. Dette feltet er beskrevet slik:

https://doc.difi.no/dcat-ap-no/#datasett-tilgangsniva[https://doc.difi.no/dcat-ap-no/#datasett-tilgangsniva]

EU Publication Office har definert de tre verdiene slik.footnote:[http://publications.europa.eu/mdr/resource/authority/access-right/html/access-right-eng.html]:

|===
|navn |beskrivelse

|non-public
|Not publicly accessible for privacy, security or other reasons. Usage note: This category may include resources that contain sensitive or personal information.

|public
|Publicly accessible by everyone. Usage note: Permissible obstacles include registration and request for API keys, as long as anyone can request such registration and/or API keys.

|restricted
|Only available under certain conditions. Usage note: This category may include resources that require payment, resources shared under non-disclosure agreements, resources for which the publisher or owner has not yet decided if they can be publicly released.

|===


==== Vurderinger

Arbeidsgruppa har avgrenset mot retten til partsinnsyn etter forvaltningsloven eller særlover fordi retten til å se opplysningene i egen sak er en annen vurdering enn spørsmålet om andre skal ha rett til å se dataene. Det er ikke det primære bruksområdet for felles datakatalog å dekke behovet for innsyn i opplysningene i egen sak. Felles datakatalog skal gi brukeren en mulighet til å se hvilke opplysninger som blir brukt ved behandlingen, men krav om innsyn i egen sak må håndteres som en del av saksbehandlingen. Et datasett som f.eks er begrenset eller ikke-offentlig vil være tilgjengelige for parten(e) i saken med de begrensningene som følger av lov.

I omtalen nedenfor er fokuset på informasjon om hvilken type tilgang som kan gis til datasettet og ikke spørsmålet om rett til viderebruk. Retten til viderebruk av personopplysninger krever er rettslig grunnlag jf https://lovdata.no/lov/2000-04-14-31/§8[popplyl § 8] og https://lovdata.no/lov/2000-04-14-31/§9[https://lovdata.no/lov/2000-04-14-31/§9[9]]. Den enkelte virksomhet må selv sikre at de har et rettslig grunnlag jf personopplysningsloven før datautveksling gjennomføres.

Arbeidsgruppa har drøftet om de tre verdiene, _offentlig_, _begrenset_ eller _ikke-offentlig_, dekker brukerbehovene. Brukerbehovet var å få informasjon om skjerming og om det er andre betingelser knyttet til bruken av datasettet. Behovet var også om de tre verdiene er tydelig avgrenset slik at det blir enkelt å forstå hvor datasettet hører hjemme.

==== Overordnet skisse


Nedenfor er det gjort et forsøk på å omtale hva som faller innenfor de ulike verdiene i feltet tilgangsnivå:

.Offentlig
I denne kategorien faller datasett som kan gjøres tilgjengelig for alle og enhver. Dette er datasett som inneholder opplysninger som faller inn under offentleglovas hovedregel og ingen unntakshjemler kommer til anvendelse (https://lovdata.no/lov/2006-05-19-16/§3[offl. § 3]).

Dette vil også omfatte datasett med opplysninger fra virksomheter som faller utenfor https://lovdata.no/lov/2006-05-19-16/§2[offenleglovas virkeområde] under forutsetning at det ikke følger av annen lov eller avtale at opplysningene skal underlegges begrensninger for gjenbruk, taushetsrett eller plikt.

Kategorien omfatter datasett der det stilles vilkår som er like for alle og ikke oppleves som særlig tyngende. Dette vil f.eks være krav om brukerregistrering/API-nøkler som er gratis.

Det kan også være krav etter åndsverksloven for viderebruk f.eks krav om kildehenvisning https://lovdata.no/lov/1961-05-12-2/§3[åvl § 3] som ikke er å anse som særlig tyngende og som er likt for alle.

Alle åpne data faller inn under denne kategorien.

Så lenge alle kan få tilgang, vil datasettet være “offentlige” ihht. dette feltet. Forutsetningen er at ev. begrensninger er like for alle for eksempel brukerregistrering/api-nøkler. Dersom begrensningen oppleves som særlig tyngende vil dataene være i kategorien _begrenset_. Særlig tyngende vil f.eks være betaling, godkjenning, avtalelisenser mv.

Innholdsmessig er forslaget i samsvar med definisjonen i EU sitt rammeverk.

“EU Publication Office: Publicly accessible by everyone. Usage note: Permissible obstacles include registration and request for API keys, as long as anyone can request such registration and/or API keys.”

.Begrenset
Datasettet kan gjøres tilgjengelig for alle og enhver på visse vilkår.

Kategorien kan omfatte datasett som

 * opplysningene er offentlige jf offl § 3, men det er knyttet andre begrensninger til bruken som vurderes å være særlig tyngende f.eks
 ** kun er tilgjengelig mot betaling for innsyn, https://lovdata.no/forskrift/2008-10-17-1119/§4[offentlegforskrifta § 4]
 ** er omfattet av opphavsrett og krav til vederlag før bruk https://lovdata.no/lov/1961-05-12-2/§35[åvl § 35]
 * er omfattet av lovbestemt taushetsrett og krever søknad og/eller konkret vurdering.
 ** lovhjemmel for utlevering av opplysningene etter en konkret vurdering. Dette er for eksempel folkeregisterloven der SKD kan vurdere utlevering av opplysningene på visse vilkår. Dersom det foreligger en slik utleveringshjemmel skal det henvises til bestemmelsen med link til lovdata.
 * er omfattet av sivilrettslige avtaler som har klausuler som begrenser offentliggjøring/gjenbruk ved å stille krav om godkjenning/samtykke, betaling osv.
 * ikke er vurdert med tanke på tilgangsnivå ennå https://lovdata.no/lov/2006-05-19-16/§5[offl § 5]

Innholdsmessig er forslaget i samsvar med definisjonen i EU sitt rammeverk.

“EU Publication Office: Only available under certain conditions. Usage note: This category may include resources that require payment, resources shared under non-disclosure agreements, resources for which the publisher or owner has not yet decided if they can be publicly released.”

.Ikke-offentlig (non-public)
Datasettet kan ikke gjøres tilgjengelig for alle og enhver fordi det er unntatt offentlighet på grunn av lovbestemt taushetsplikt jfhttps://lovdata.no/lov/2006-05-19-16/§13[ offl § 13].  +
Taushetsplikten vil typisk dekke personlige forhold (herunder hemmelig adresse og de fleste sensitive personopplysninger) og forretningshemmeligheter, jf. fvl § 13. Videre kan opplysningene i datasettet ikke gjøres tilgjengelig fordi det omfattes av reglene i https://lovdata.no/lov/2006-05-19-16/§5[offl kapittel 3] for unntak fra innsynsretten.

Innholdsmessig er forslaget i samsvar med definisjonen i EU sitt rammeverk.

“EU Publication Office: Not publicly accessible for privacy, security or other reasons. Usage note: This category may include resources that contain sensitive or personal information.”

Vi gjør oppmerksom på at datasett som omfattes av kategorien ikke-offentlig på grunn av taushetsplikt kan utveksles dersom det faller inn under et av unntakene fra taushetsplikten i https://lovdata.no/lov/1967-02-10/§13a[forvaltningsloven §§ 13 a-f]. Denne konkrete vurderingen vil gjelde for alle datasett og er av en litt annen type enn de datasettene som omfattes av lovbestemt taushetsrett som er omtalt i kategorien begrenset. Vi mener det derfor vil være mest hensiktsmessig å legge datasett som i utgangspunktet omfattes av taushetsplikten under kategorien ikke-offentlig, men at det i bestemte situasjoner kan gjøres unntak jf fvl §§ 13 a-f.

.Hva hvis et datasett inneholder opplysninger som naturlig faller i flere av kategoriene?

Dersom datasettet inneholder både taushetsbelagt informasjon (ikke-offentlig) og det kreves f.eks lisens eller betaling for bruk (transaksjonskostnader) er det et behov for å kunne krysse av på både begrenset og ikke-offentlig. I dag er de tre kategoriene/verdiene alternativer, dvs at det bare kan krysses av for en verdi og ikke kombineres. En tilpasning kan gjøres på ulike måter. Ett forslag er å ha som prinsipp at verdien ikke-offentlig må velges dersom datasettet inneholder skjermede opplysninger og at det etableres et nytt eget felt for krav om betaling knyttet til bruk av datasettet. Et annet forslag er å åpne opp for avkrysning av både begrenset og et av de andre to andre kategoriene.

Begge forslagene fører til et behov for tilpasninger i den norske DCAT-standarden. Så vidt vi forstår vil dette ikke være en løsning fordi det vil være i strid med retningslinjene for bruk av DCAT å krysse av for flere av alternativene. Det er tatt til orde for at dersom det er behov for å krysse av for flere alternativer kan det tyde på at datasettet bør deles opp. Arbeidsgruppen tror at det i praksis vil være situasjoner der det både er taushetsbelagte opplysninger og begrensninger som bør komme frem på en eller annen måte samtidig som det ikke er naturlig eller hensiktsmessig å dele opp datasettet. En mulig løsning vil kunne være å krysse av for en av alternativene og dekke behovet for informasjon om krav til betaling under skjermingshjemmel.

Arbeidsgruppen anbefaler at de tre verdiene er alternativer som i dag, men at behovet for informasjon om begrensninger løses under skjermingshjemmel, se nedenfor.

==== Veileder

Difi sin veileder for beskrivelse av datasett i henhold til DCAT-AP-NO er under revidering så det har liten verdi å gjengi nåværende veiledningstekst.

Arbeidsgruppens anbefaling er å tydeliggjøre noen punkter i veilederen:

 * de tre verdiene dekker ulike områder og det er rimelig tydelig i hvilken verdi et datasett skal plasseres. Det kan imidlertid være vanskelig for de som skal fylle ut metadata å vurdere hvilken verdi datasettet hører under fordi det krever kunnskap og en rettslig vurdering etter offentleglova, forvaltningsloven mfl. Denne utfordringen kan ikke løses ved å øke antallet verdier, men må løses ved tiltak i forvaltningen i den enkelte etat. Dette bør omtales nærmere i veilederen.

 * veilederen oppdateres i samsvar med beslutningen om nytt felt for betalingsvilkår

 * det må også presiseres at dersom datasettet inneholder noen opplysninger som er taushetsbelagte eller skjermet må verdien ikke-offentlig (skjermet) velges. Kategoriseringen skal gjenspeile det mest begrensede feltet/opplysningen i datasettet. Varianter (utsnitt) av datasettet kan være åpnere ved at man utelater opplysninger som gjør at det opprinnelige datasettet er begrenset eller ikke-offentlig se eksempel på#heading=h.oq9cvdbasqzo[ to datasett fra Brønnøysundregisteret med og uten fødsels- og D-nummer.]
 * ved bruk av verdien "ikke-offentlig" er egenskapen skjermingshjemmel obligatorisk.

=== Beskrivelse av skjermingshjemmel [[beskrivelse-skjermingshjemmel]]

==== Anbefaling

Dersom datasettet inneholder begrenset eller skjermet informasjon, mener arbeidsgruppen det bør være anbefalt at skjermingshjemmel angis med henvisning til hjemmelsgrunnlaget.

Arbeidsgruppen anbefaler å benytte https://doc.difi.no/dcat-ap-no/#datasett-skjermingshjemmel[feltet “skjermingshjemmel” i DCAT-AP-NO v.1.1]. Det er besluttet i siste revisjonsrunde for DCAT-AP-NO at det skal utarbeides et SKOS-vokabular (katalog) med aktuelle skjermingshjemler der det kan være en referanser til lovdata.

For å dekke behovet for informasjon om betaling anbefales det at det blir et eget alternativ i SKOS-vokabularet (katalogen) for skjermingshjemler, og derfra en lenke til prisinformasjon i den aktuelle loven, jf reglene i https://lovdata.no/lov/2006-05-19-16/§8[offl § 8].

For å dekke behov for å kunne oppgi skjermingshjemler som ikke står i ovennevnte skos-vokabularet (katalogen), anbefaler arbeidsgruppen å opprette et nytt valgfritt felt der man kan oppgi lenke (URI) til aktuell lov.

==== Brukerbehovet

Dersom opplysninger som en offentlig etat har er ikke-offentlige trenger brukerne av felles datakatalog å få kunnskap om hva som er grunnlaget for skjermingen av opplysningene. Dette er vesentlig informasjon for å vurdere om brukerens eget regelverk for innhenting av opplysninger fra andre har hjemler som dekker.

Det er også et behov for informasjon om krav på betaling for bruk av datasettet. Denne informasjonen er det viktig at brukeren får tidlig i en utredningsfase ved regel- og tjenesteutvikling og tilrettelegging for kontrollaktiviteter. Det må derfor være mulig å få denne informasjonen i tillegg til skjermingshjemmel. Arbeidsgruppen har ikke mulighet til å angi den konkrete løsningen for denne funksjonaliteten, men forutsetter at det videre arbeidet legges til rette for å dekke brukerbehovet.

==== Eksempler

I rollen som saksbehandler i Arkivverket trenger jeg å vite hvilke opplysninger i et arkivverdig datasett som eventuelt er unntatt offentlighet, og i tilfelle på hvilket rettslig grunnlag, for å kunne vurdere innsynsbegjæringer etter at opplysningene er avlevert til Arkivverket og rådigheten overført til Riksarkivaren.

I rollen som bruker i SSB av informasjon fra offentlige virksomheter trenger vi å se det juridiske grunnlaget for skjerming av informasjon for å kunne vurdere om vår innhentingshjemmel trumfer deres skjermingshjemmel.

I rollen som etterforsker i politiet av en potensiell straffesak trenger jeg det juridiske grunnlaget for skjerming av informasjon for vurdere om vår innhentingshjemmel trumfer deres skjermingshjemmel.

==== Feltdefinisjon

I DCAT-AP-NO 1.1 er “skjermingshjemmel” omtalt slik:

https://doc.difi.no/dcat-ap-no/#datasett-skjermingshjemmel[https://doc.difi.no/dcat-ap-no/#datasett-skjermingshjemmel]

I tillegg, et nytt felt: valgfritt med URI til lovdata.

==== Veileder

I Difi sin https://doc.difi.no/data/veileder-for-beskrivelse-av-datasett[veileder for beskrivelse av datasett (DCAT-AP-NO)] er begrensninger i tilgangsrettigheter omtalt slik:


.Innspill til veileder:

Arbeidsgruppen anbefaler at teksten i veilederen omskrives slik at den gjenspeiler definisjonen av _ikke-offentlig_ i DCAT. Vi mener det er uheldig å bruke overskriften sensitivt innhold fordi dette raskt tolkes til å være sensitive personopplysninger. Det anbefales at man benytter _ikke-offentlig_ eller _skjermet_ som overskrift og tydeliggjør i teksten at dette vil omfatte taushetsbelagte opplysninger som også kan være sensitive personopplysninger osv.

=== Beskrivelse av utleveringshjemmel

==== Anbefaling

Arbeidsgruppen anbefaler at det etableres et felt for registrering av hjemmel til utlevering av opplysninger. Feltet bør være anbefalt for datasett som er klassifisert som ikke-offentlige/skjermet. Feltet er anbefalt og skal fylles ut dersom det finnes utleveringshjemmel. Angis som lenke til Lovdata.

==== Behov

Brukerhistoriene viser at informasjon om utleveringshjemmel gjør det enklere for brukere av datakatalogen å se om det er nødvendig med egen hjemmel for innhenting eller om de kan få tillatelse til å bruke opplysninger etter søknad til registereier.

==== Eksempel - myndighetsutøvelse/etterlevelse og kontrollformål

Lånekassen har behandlingsgrunnlag, men ikke hjemmel til datafangst direkte fra SKD i innhentingsforskriften til utdanningsstøtteloven for enkelte av opplysningene i folkeregisteret som brukes til kontroller. Lånekassen har søkt Folkeregisteret om utlevering av personopplysningene og fått innvilget utlevering av opplysningene jf vedtak fra Folkeregisteret om utlevering etter https://lovdata.no/lov/1970-01-16-1/§14[folkeregisterloven § 14] jf. https://lovdata.no/forskrift/2007-11-09-1268/§9-3[forskriften § 9-3]. NB - Dette eksempelet vil bortfalle om noe tid fordi folkeregisterloven endres slik at alle etater må etablere egne regler i særlov/forskrifter for å kunne innhente opplysninger fra folkeregisteret.

Kartverket trenger i rollen som forvalter av matrikkelen å vite det juridiske grunnlaget for om vi kan hente inn personadresser fra folkeregisteret for videreformidling og til bruk av matrikkeldata.

==== Feltdefinisjon

Det vil være behov for et tillegg i den norske versjonen av DCAT-AP-NO.

.Forslag til definisjon
Henvisning til regelverk som begrunner en offentlig virksomhet sin rett eller plikt til å utlevere opplysninger til andre private personer eller juridiske personer.


==== Veileder

Feltet må få en forklarende tekst i veilederen slik at feltet fylles ut på en god måte og det blir enklere å forstå.

=== Forslag til formalisert henvisning til regelverk

Gruppen foreslår at i den grad det skal gis henvisninger til regelverk i datakatalogen, bør de så langt det er mulig uttrykkes på en standardisert måte (formalisert). Under er noen forslag til hvordan dette kan løses:

 * bruke kortlenker i Lovdata på forskjellige nivåer (dette finner en ved å trykke på “dele ikonet” i bestemmelsen og kopiere “kort lenken” som vises.) Her må det vurderes å bruke ELI, for å sikre best mulig samhandlingsevne på tvers av landegrenser, https://lovdata.no/eli/norsk[https://lovdata.no/eli/norsk]
 * direkte API mot Lovdata slik at en kan legge inn henvisning direkte i datakatalogens GUI.
 * bruke ferdige lister (SKOS-vokabular) med lenker til Lovdata som utarbeides i felles datakatalog

Fordelen ved å benytte formaliserte henvisninger til lovverket vil senere gjøre det mulig å finne datasett via lovverket. For jurister og andre som kjenner regelverket og jobber mye med dette antar vi at det kan være et godt hjelpemiddel for å få oversikt f.eks i forbindelse med utredning av lov og forskriftsendringer.

Det bør være mulig å henvise til forskjellige nivåer i lovverket. For eksempel henvise til en lov og forskriftsbestemmelse, kapittel/paragraf/ledd/punktum/bokstav eller til hele regelverket. Dette er ikke på plass ennå, men det forutsettes at dette utvikles videre i samarbeid med Lovdata slik at denne funksjonaliteten blir gratis tilgjengelig for alle.

==== Brukerbehov

I rollen som dataeier i SSB trenger vi å kunne referere enhetlig/standardisert til hjemmelsgrunnlag for skjerming av informasjon for å kunne oppnå høy grad av maskinlesbarhet.
