
== Spesifikasjon for hvordan TBX brukes ved maskinell tilgjengeliggjøring av begrepsbeskrivelser

Spesifikasjonen i dette kapitlet utgjør definisjonen av en TBX-dialekt, kalt TBX-AP-No. Dialektnavnet TBX-AP-No skal oppgis i en TBX-fil for å være i samsvar med denne standarden: <tbx type="TBX-AP-No">.

Spesifikasjonen sier ikke hva som er obligatoriske felter, men hvordan et felt skal representeres i TBX når feltet brukes. Se Forvaltningsstandard for begrepsbeskrivelser hhv. TBX for hva som er obligatorisk. 

For referanser fra et begrep til andre begreper, har vi valgt å bruke <xref>, også i tilfeller begreper som refereres til er i samme TBX-fil. Dette fordi Forvaltningsstandard (legg til lenke) for begrepsbeskrivelser krever at ethvert begrep skal ha en URI. 

I tabellen under er det også tatt med PID (persistent identifier) til definisjoner av datafelter og kodeverdier. Dette for å oppnå semantisk interoperabilitet med andre TBX-dialekter, ved at man gjennom unike PIDer refererer til samme definisjoner av datafelter og kodeverdier, selv om man bruker ulike termer i ulike TBX-dialekter. Vi bruker primært PIDer som finnes fra ISO http://www.isocat.org/datcat/[(www.isocat.org/datcat/)], supplert med definisjoner/PIDer fra andre offisielle kilder (bl.a. https://www.w3.org/TR/skos-reference/[SKOS] og http://dublincore.org/documents/dcmi-terms/[Dublin Core]). Der det p.t. ikke finnes ferdige internasjonale definisjoner, er PID oppgitt med prefiks “skosno:”. Disse vil bli definert og publisert senere under vokab.norge.no/skosno#. PIDer er ikke nødvendig å oppgi i en TBX-fil, men brukes til å slå opp i definisjoner når man implementerer eller tolker en TBX-fil som er i samsvar med denne standarden. 

Se ellers eksemplene i vedlegget til dette dokumentet
