== Gjeldende lovverk og IKT-politikk for åpne offentlige data

Statens IKT-politikk for tilgjengeliggjøring av offentlige data er beskrevet i https://www.regjeringen.no/no/dokumenter/meld.-st.-27-20152016/id2483795/[Digital agenda for Norge] som _gjenbruk _og _viderebruk_, der _gjenbruk _er offentlige virksomheters bruk av offentlige data (kapittel 7), mens _viderebruk _er privat sektors og sivilsamfunnets bruk av offentlige data (kapittel 14). 

Regjeringens mål om økt viderebruk er knyttet til målene om effektivisering og innovasjon, næringsutvikling og et åpent og demokratisk samfunn. Stortingsmeldingen trekker frem fem sektorer hvor viderebruk anses som samfunnsøkonomisk verdifulle: kultur, forskning og utdanning, statlige utgifter, transport og samferdsel og kart og eiendom (Geodata). 

Regjeringens føringer for deling av åpne offentlige data er regulert i https://lovdata.no/dokument/NL/lov/2006-05-19-16?q=offentleglova[Lov om rett til innsyn i dokument i offentleg verksemd] (offentleglova),  https://www.regjeringen.no/id2569983/ [Digitaliseringsrundskrivet] og regjeringens https://www.regjeringen.no/no/id2536870[Retningslinjer ved tilgjengeliggjøring av offentlige data]

==== Offentleglova

https://lovdata.no/NL/lov/1814-05-17-nn/§100[Grunnlova § 100] slår fast at “alle har rett til innsyn i dokument til staten og kommunane. Retten til innsyn er presisert i offentleglova. Hovedregelen i offentleglova § 3 er at alle “saksdokument, journalar og liknande register for organet” er offentlig, det vil si omfattet av innsynsrett. Dokumentbegrepet i offentleglova er definert som “ei logisk avgrensa informasjonsmengd” og omfatter dermed også data som offentlig sektor forvalter. Offentleglova skal blant annet legge til rette for viderebruk av offentlig informasjon, og at offentlige sektor er åpen og gjennomsiktig (jf. https://lovdata.no/NL/lov/2006-05-19-16/§1[offentleglova § 1])

Informasjon som det er gitt tilgang til etter offentleglova kan brukes til ethvert formål, dersom ikke annen lovgivning eller retten til en tredjeperson er til hinder for det. Personopplysningsretten og opphavsretten er eksempler på rettigheter som begrenser muligheten for viderebruk.

Retten til innsyn er ikke ubegrenset. Mange dokumenter _skal_ eller _kan_ unntas fra offentlighet. Lovbestemt taushetsplikt unntar personlige forhold og forretningshemmeligheter fra innsynsretten. Dokumenter som kan lette gjennomføring av straffbare forhold, eller dokumenter som regnes som interne, kan unntas fra innsynsretten.

En oppdatering av Offentleglova i 2017 gir nå allmennheten rett til innsyn i alle eksisterende formater og språkversjoner av informasjonen det bes om innsyn i. Denne plikten gjelder også maskinlesbare formater.

Offentleglova gir altså allmennheten innsynsrett, det vil si at informasjon vil bli gjort tilgjengelig på forespørsel. Dette kan beskrives som en _reaktiv åpenhet, _og innsyn forutsetter at allmennheten har tilstrekkelig kunnskap til å stille relevante innsynskrav. Digitaliseringsrundskrivet legger opp til en mer _proaktiv åpenhet_,__ __der egnet informasjon _skal _ gjøres tilgjengelig i maskinlesbare formater og synliggjøres på https://data.norge.no/[data.norge.no].

==== Digitaliseringsrundskrivet

Digitaliseringsrundskrivet gjelder for departementene, statens ordinære forvaltningsorganer, forvaltningsorganer med særskilte fullmakter og forvaltningsbedrifter.

Rundskrivet slår fast at den enkelte virksomhet skal ha oversikt over hvilke data den håndterer, hva dataene betyr, hva de brukes til, hvilke prosesser de inngår i, og hvem som kan bruke dem. Dette innebærer altså at forvaltningen må ta stilling til hvilke data som kan gjøres tilgjengelig som åpne offentlige data, og ta stilling til hvilke data som skal prioriteres først, for eksempel etterspurte eller samfunnsviktige data andre ikke har.

Rundskrivet (punkt 1.3) slår også fast at virksomheten skal “gjøre egnet informasjon tilgjengelig for viderebruk i maskinlesbare formater, fortrinnsvis gjennom APIer”. Dette gjelder når virksomhetene etablerer nye eller oppgraderer eksisterende fagsystemer. Videre pekes det på at tilgjengeliggjøring av data skal skje i samsvar med regjeringens https://www.regjeringen.no/no/dokumenter/retningslinjer-ved-tilgjengeliggjoring-av-offentlige-data/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] og viderebruksbestemmelsene i offentleglova.

==== Retningslinjer ved tilgjengeliggjøring av offentlige data

Regjeringens https://www.regjeringen.no/no/dokumenter/retningslinjer-ved-tilgjengeliggjoring-av-offentlige-data/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] er en føring som består av 15 punkt og skal sikre best mulig utnyttelse av offentlige data. De mest grunnleggende punktene omhandler fraskrivelse av eventuell opphavsrett ved å bruke åpne standardlisenser, å tilby data gratis og å tilby data i maskinlesbare og standardiserte formater. Se kapitlet _Klargjøring og publisering - hvordan bør du tilby data?_  for mer informasjon om retningslinjene.
