
== Lisensiering av data

Hvilke rettigheter har jeg? Hva betyr det å lisensiere data? Hvilken lisens burde jeg bruke? Hvordan kan jeg angi lisensen som datasettet er tilgjengelig under? Hva kjennetegner en _åpen_ lisens? 

Det meste av offentlig sektor sine produkter (f.eks registre, rapporter, nettsider, bilder og datasett) er underlagt åndsverkloven. Denne beskyttelsen begrenser i stor grad hva brukeren kan gjøre med innholdet. For eksempel kan ikke andre fremstille kopier, oversettinger, tilpasninger eller konverteringer til andre format.

Det er to ulike rettigheter som er nedfelt i åndsverkloven og som automatisk følger med de tingene du (og din virksomhet) skaper:
 

* Du får *opphavsrett* til innhold som du lager og som er originale for deg og din virksomhet, som for eksempel tekst du skriver eller bilder du tar.
* Du får *databaserettigheter *over “_et formular, en katalog, en tabell, et program, en database eller lignende arbeid som sammenstiller et større antall opplysninger, eller som er resultatet av en vesentlig investering_” (https://lovdata.no/dokument/NL/lov/2018-06-15-40/KAPITTEL_3-3#%C2%A743[åndsverksloven §43]). Denne rettigheten er også omtalt som “katalogvern”

I vår sammenheng er det databaserettighetene som er mest relevante. En database er vernet i 15 år etter at den ble fremstilt, eventuelt 15 år etter den første gang ble offentliggjort. En database som jevnlig oppdateres vil i praksis ha et rullerende vern, ved at det stadig fremstilles nye versjoner av basen.

Ettersom opphavsrett og databaserettigheter er automatiske vern, må de som ønsker å bruke informasjonen din ha din tillatelse. Ved å bruke lisenser kan du gi fra deg denne eneretten, slik at brukerne ikke må spørre deg om lov. Lisensen tydeliggjør hva brukerne har lov til å gjøre med innholdet.

Potensiale for bruk av data begrenses vesentlig dersom datasettene ikke har en åpen lisens. Restriksjoner på innhold som offentlig sektor har skapt, kan bidra til lav effektivitet både i offentlig og privat sektor, og kan være til hinder for etablering av nye og innovative produkter og tjenester. Regjeringens https://www.regjeringen.no/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] legger opp til at offentlige virksomheter skal si fra seg egne rettigheter for datasett de forvalter ved å bruke åpne standardlisenser.

NOTE: Du kan bare lisensiere informasjon som virksomheten selv har rettighetene til, eller som du har fått tillatelse av eieren til å lisensiere. En slik tillatelse kan for eksempel være at data fra tredjepart er publisert under en åpen lisens.

=== Hva er åpne lisenser?

En åpen lisens er en generell avtale mellom deg som datatilbyder og brukerne av dine data som inneholder svært få restriksjoner for brukerne. En åpen lisens tillater for eksempel at andre kan: 

* tilgjengeliggjøre dine data på egne hjemmesider
* trekke ut data fra din tjeneste eller ditt produkt
* tjene penger ved å selge produkt eller tjenester som bruker dine data
* tilgjengeliggjøre data og ta betalt for tilgang

Åpne standardlisenser kan deles inn i ulike typer. Disse tre er de viktigste: 

*“Public domain”-lisenser* har ingen restriksjoner og innebærer en fraskrivelse av alle rettene du har til data. Det beste eksemplet på en “public domain”-lisens er  https://creativecommons.org/share-your-work/public-domain/cc0/[Creative Commons Zero] (CC0).

*Navngivelse lisenser* krever at brukerne må oppgi deg (din virksomhet) som kilde i sitt produkt. Eksempler her er  https://creativecommons.org/licenses/by/4.0/deed.no[Creative Commons Navngivelse 4.0 (CC 4.0-BY)] og https://data.norge.no/nlod/[Norsk lisens for offentlige data (NLOD)].

*Navngivelse - del på samme vilkår.* En slik lisens krever at brukerne deler sitt produkt under de samme vilkår som originalen. I Norge er ikke lisenser av denne typen anbefalt for data fra offentlig sektor, ettersom de begrenser mulighetene for kommersiell bruk i for stor grad. I noen tilfeller _kan_ en slik lisens likevel være et alternativ, for eksempel når bidragsytere ønsker å begrense mulighetene for kommersiell bruk i forbindelse med at +
offentlige data berikes med data som samles inn på dugnad (crowdsourcing). 

Øvrige lisenser som ikke tillater kommersiell bruk, regnes ikke som åpne lisenser i denne sammenhengen.

NOTE: Vi er spesielt opptatt av strukturerte data i denne veilederen, men alle Creative Commons 4.0-lisenser dekker andre typer innhold med opphavsrett som tekst, video og bilder. NLOD-lisensen dekker kun strukturerte data. 

=== Hvilke lisens bør jeg velge?

De to lisensene som er anbefalt brukt av Kommunal- og moderniseringsdepartementet er begge navngivelse-lisenser: https://creativecommons.org/licenses/by/4.0/deed.no[Creative Commons Navngivelse 4.0 (CC 4.0-BY)] og https://data.norge.no/nlod/[Norsk lisens for offentlige data (NLOD)]. Dersom du velger CC 4.0-BY legger du bedre til rette for internasjonal bruk.

Du kan også vurdere å bruke Creative Commons Zero (CC0). Du sier da fra deg alle rettigheter til datasettet, inkludert retten til å bli oppgitt som kilde.
