
=== Lokal datakatalog

Ettersom DCAT-AP-NO er basert på en internasjonal standard finnes det flere løsninger som kan benyttes til etablering av en lokal datakatalog. Samtidig vil de norske tilleggene medføre at de må tilpasses noe for å støtte norske tillegg. Felles datakatalog, som utvikles og forvaltes av Brønnøysundregistrene, er en lavterskel løsning som støtter alle de særnorske tilleggene. Kildekoden til Felles datakatalog ligger på https://github.com/Altinn/fdk/blob/master/README.md[GitHub], og Difi anbefaler å implementere denne løsningen lokalt.

Ved mer komplekse behov finnes andre løsninger som kan benyttes til en lokal datakatalog, f.eks:

https://ckan.org/[CKAN] : en komplett løsning for både beskrivelse og distribusjon av datasett. Støtter eksport til de fleste egenskapene i DCAT-AP om en bruker http://extensions.ckan.org/extension/dcat/[denne utvidelsen]. Statens vegvesen har utviklet https://github.com/vegvesen/ckanext-dcat_ap_no[et programtillegg] som også ivaretar de norske utvidelsene.

http://getdkan.com/features/[DKAN]: En løsning bygget på publiseringsløsningen Drupal. Kort om forskjellen på DKAN og CKAN finner du http://docs.getdkan.com/en/latest/introduction/dkan-ckan.html[her].

http://thedatatank.com/[The datatank:]  En løsning med fokus på distribusjon av datasett, men som også støtter beskrivelser av datasett i tråd med DCAT-AP.

https://entryscape.com/en/products/catalog/[Entryscape Catalog]: Svensk programvare (og teneste) som i motsetning til flere av de andre løsningene er basert på DCAT-AP.  Har i tillegg støtte for DCAT-AP-NO.

Flere av disse løsningene er komplette plattformer i den betydningen at de også har funksjonalitet for å distribuere datasett. Listen er ikke uttømmende og løsningene er ikke testet av Difi.
