
== 4. Spesifikasjon for hvordan SKOS brukes ved maskinell tilgjengeliggjøring av begrepsbeskrivelser

Tabellen under viser hvordan SKOS brukes til å representere de ulike feltene i _Forvaltningsstandard for begrepsbeskrivelser_. Se ellers eksemplene i vedlegget til dette dokumentet.

SKOS er et lite vokabular (metamodell) for de mest sentrale klassene og egenskapene for begreper (concept). For å bruke SKOS som representasjonsspråk i begrepsbeskrivelser må vokabularet utvides med andre vokabularer. Denne standarden supplerer SKOS med følgende vokabularer:about:blank[[.underline]#dct:#]dcat

* ____
http://purl.org/dc/terms/[[.underline]#dublin core terms (DCT)#] (i tabellen under med prefiks dct:) - supplerer med generelle egenskaper knyttet til dokumentasjon
____
* ____
http://www.w3.org/ns/dcat#[[.underline]#data catalog vocabulary (DCAT)#] (i tabellen under med prefiks dcat:) - supplerer med generelle egenskaper knyttet til datasett
____
* ____
http://www.w3.org/2008/05/skos-xl#[[.underline]#SKOS extension for labels (SKOS-XL)#] (i tabellen under med prefiks skosxl:) - supplerer med egenskaper knyttet til termer
____
* ____
http://rdf-vocabulary.ddialliance.org/xkos#sem-props[[.underline]#SKOS extension for representing statistical classifications (XKOS)#] (i tabellen under med prefiks xkos:) - supplerer med egenskaper knyttet til relasjoner
____
* ____
Norske SKOS-utvidelser (i tabellen under med prefiks skosno:) - det som etter bruk av ovennevnte suppleringer fortsatt mangler, vil suppleres med egne norske utvidelser til SKOS. Norske utvidelser til SKOS vil bli definert og gjort tilgjengelig senere via vokab.norge.no/skosno#.
____
