
=== Felter som er maskingenerert

==== Identifikator for datasett

For å kunne referere til et datasett entydig og kunne angi relasjoner mellom datasett, må alle datasett ha stabile, globale og unike identifikatorer. Identifikator er et obligatorisk felt.

* Identifikatoren bør automatisk genereres når du registrerer datasettet om du benytter en registreringsløsning.
* Identifikatoren skal være unik innenfor aktuell datakatalog
* Identifikatoren skal inngå i en globalt unik identifikator.
* Den globalt unike identifikatoren skal utformes som en URI
* Den globalt unike identifikatoren er representert ved feltet dct:identifier
* Datasettets URI bør benytte en av de globalt unike identifikatorene i dct:identifier
* Man bør kunne registrere ytterligere identifikatorer.


.Eksempler
* [*] “http://data.brreg.no/datakatalog/datasett/12”

----
<http://data.brreg.no/datakatalog/datasett/12>
   dct:identifier “http://data.brreg.no/datakatalog/datasett/12” ;
   adms:identifier <http://data.brreg.no/datakatalog/identifikator/111> ;
   owl:sameAs <http://datakatalog.hdir.no/datasett/2.16.528.1.12.1.1.7110> .

# identifikatoren for datasettet innenfor Helsedirektoratet
<http://data.brreg.no/datakatalog/identifikator/111>
   a adms:Identifier ;
   skos:notation “OID 2.16.578.1.12.4.1.1.7110” ;
   dct:creator <http://data.brreg.no/enhetsregisteret/enhet/983544622> #helsedir
   .
----

NOTE: Titlene under samsvarer med egenskapsnavnene i DCAT-AP-NO v1.1. Titler i parentes er brukt i registreringsløsningen for Felles datakatalog. Felter i registringsløsningen som ikke er del av standarden er merket med * . Det eksisterende gapet mellom standard og løsning er forventet løst i en snarlig revisjon av standarden.  
