== Hvorfor orden i eget hus?

Data er en av de viktigste ressursene i offentlig sektor, og i samfunnet, og det har lenge vært et krav om at offentlig sektor må utnytte dette bedre for å bli mer effektiv, gi bedre tjenester til innbyggere og næringsliv, og bidra til økt rettssikkerhet.

* Digitaliseringsrundskrivet footnote:[https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2569983/ er en sammenstilling av pålegg og anbefalinger vedrørende digitalisering i offentlig sektor, og gir et helhetlig bilde av hvilke føringer som gjelder.]  konkretiserer dette ved bl.a. å si at offentlige virksomheter i størst mulig grad bør gjenbruke informasjon som allerede finnes.
* Stortingsmeldingen “Digital agenda for Norge - IKT for enklere hverdag og økt produktivitet” fokuserer også på datautveksling og gevinster ved gjenbruk. Helhetlig informasjonsforvaltning nevnes også som en forutsetning for å oppnå målet om “kun-en-gang”, som også EU jobber for.
* Lov om Oppgaveregisteret er enda sterkere og stiller krav om samordning rundt innhenting av informasjon fra næringslivet. Formålet med dette er bl.a. å fremme en datadelingskultur i offentlig sektor.

En større grad av gjenbruk krever imidlertid en helhetlig styring og forvaltning av informasjon, både internt i og på tvers av virksomheter, og mange offentlige virksomheter har nå en felles forståelse av at manglende oversikt over egen informasjon - eller manglende “orden i eget hus” - er et av de viktigste hindrene for elektronisk informasjonsutveksling, og dermed gjenbruk av andres informasjon. Skate footnote:[Skate (Styring og koordinering av tenester i e-forvaltning) er eit strategisk samarbeidsråd som skal bidra til at digitaliseringa av offentleg sektor blir samordna og gjev gevinstar for innbyggjarar, næringsliv og forvaltninga https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/skate ] har derfor informasjonsforvaltning høyt på agendaen, og denne veilederen for “orden i eget hus” er en del av denne satsingen.
