
=== Legitimitet og tillit

Riktig datagrunnlag er avgjørende for å trygge likebehandlingen og rettssikkerheten til innbyggerne. Med bedre kvalitet på dataene legger en grunnlaget for å treffe rett avgjørelse. God orden i form av autorative kilder til informasjon vil profesjonalisere forvaltningen av disse kildene, og økt bruk vil føre til bedre kvalitet på dataene.

Innbyggerne må få innsyn i beslutningsgrunnlaget i saker som gjelder dem selv. Riktige data i beslutningsprosessene er avgjørende for tilliten til forvaltningen og de beslutningene som fattes (https://lovdata.no/dokument/NL/lov/1967-02-10[Forvaltningsloven]). Økt effektivisering i form av økt automatisering i saksbehandlingen og på sikt bruk av kunstig intelligens bygger på en forutsetning om orden i eget hus.

Innsyn i offentlig forvaltning er viktig for demokratiet, for likebehandling og i kampen mot korrupsjon og maktmisbruk. Orden i eget hus legger grunnlaget for transparens fordi vi kan gi tilgang til grunnlaget for beslutninger og prioriteringer. Vi kan gi innsyn i hvordan beslutninger følges opp, samt hva effekten av politiske tiltak er.
