
=== Overordnet organisering, roller og prosesser

Masterdata og begrepsarbeid henger tett sammen. Styring og håndtering av masterdata (master data management (MDM)) i en virksomhet er kjernen i en vellykket gjennomføring. Det å få kontroll på hvilke registre eller datasett som utgjør kjernevirksomheten kan lett knyttes til interne prosesser som vil bli mer effektive, oversiktlige og kvalitetsmessig bedre. En leder for et område vil kunne ønske å delta i arbeidet med å definere hva det fagområdet betyr fordi konsekvensen av den definisjonen vil få praktiske betydninger, bl.a. for samvirkende systemer. Er kunde udefinert, vil det kunne være krevende å vite nøyaktig hva som kreves for å telle antall kunder. Gjelder en definisjonen for globale kunder som handler i flere land, kundebestillinger per land, eller noe annet?

==== Styringsmodeller

Det blir behov for en styringsmodell for å fordele ansvar på ulike nivåer i organisasjonen ettersom arbeidet med orden i eget hus skrider frem. Ved å involvere ulike personer, og vite hvilke rolle de potensielt kan få, vil det også synliggjøre for deg hvilke argumenter du bør bruke for å få dem med i arbeidet. Avhengig av størrelsen på organisasjonen og antall ressurser til rådighet, kan en slik styringsmodell bestå av et sted mellom to til fire nivåer. Noen av rollene kan fylles av de samme enkeltindividene. Et utvalg av roller beskrives overordnet under:

* Ledergruppen utgjør ofte styringsgruppen og består av senior-ledere som dekker alle funksjoner  i organisasjonen. De styrer strategisk retning og tar budsjettavgjørelser. For å få fart og prioritering er det lurt å få disse ombord, men ta gjerne med deg et case og noen andre interessenter før du presenterer saken din i et ledermøte. Prosjektet bør ha en eier i ledergruppen som kan være den med overordnet ansvar for informasjonsforvaltningsstrategien og/eller styrende dokumenter.
* Et “råd” for informasjonsforvaltning består av ledere innen utvalgte fagområder. De er modne, eller lar seg modne, i forståelsen for hvorfor dette gjøres og er inneforstått med ansvaret de har. De bidrar til å overholde strategien og tilbyr veiledning om retning til ulike fagområder. De prioriterer innsatsområder, finansieringsprosjekter og styrer måleindikatorer for sine deler av virksomheten.
* En arbeidsgruppe består av eksperter og ledere innen fag og IT og må kunne navigere mellom fagområder og IT. Gjennomfører administrative oppgaver og avklaringer og sørger for at de ulike enhetene snakker sammen eller koordinerer innsatsen.
* Ofte vil det finnes ett eller flere støtteteam, som har overlappende/tilgrensende oppgaver. De består av en manager eller eier av datasett. I tillegg består støtten av de som er praktiske tilretteleggere og forvaltere av de daglige oppgavene for datasettene i systemene. De er avgjørende for gjennomføringen av endringer og oppdateringer og faktisk tilgang til data på tvers av ulike løsninger.
* Brukere av data i en virksomhet utgjør også en viktig støtte for et informasjonsforvaltnings”lag”. Data scientists er blitt populære, men også de er avhengige av tilgjengelige data, og deler av informasjonsforvaltningsteamet vil ha nytte av tilbakemeldinger om hvor enkelt eller vanskelig det er å nyttegjøre seg av datasett og metadata. Analytikere, personvernombudet, produkt- og systemeiere med flere vil være nyttige å ha med som støttende medspillere.

Det finnes gjerne en todeling mellom de som er sentrale styrings- og forvaltningsansvarlige for informasjon og data i virksomheten, og de som er ansvarlig for de ulike funksjonelle fagområdene. Det viktigste i en slik styringsmodell er at ansvaret for datasett og metadata ligger hos fagsiden og eiere av tjenester og produkter. Informasjonsforvaltningsgruppen støtter fagsiden i deres arbeid.
