== Forord

Difi har ansvaret for å forvalte en oversikt over anbefalte og obligatoriske IT-standarder i forvaltningen - https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/referansekatalogen[_Referansekatalogen]_. _Referansekatalogen___ __er etablert for å sikre at innbyggere og næringsliv får tilgang til offentlig informasjon og tjenester på en standardisert måte (uavhengig av brukerutstyr), sikre god samhandling mellom offentlige virksomheter, hindre bindinger til bestemte leverandører og sikre god konkurranse i IT-markedet.

Difi utreder, hører og beslutter anbefalte krav som inngår i _Referansekatalogen_. Disse kravene skal følges med mindre virksomheten har en god grunn til å la være. Obligatoriske krav utredes og høres av Difi. Høringen oppsummeres og oversendes Kommunal- og moderniseringsdepartementet, som fremmer revidert https://lovdata.no/dokument/LTI/forskrift/2013-03-15-285[_Forskrift om IT-standarder i offentlig forvaltning]_ med nye obligatoriske krav til beslutning i regjeringen.

IT-ministeren satte i 2006 ned et bredt sammensatt https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/standardiseringsradet[Standardiseringsråd] med medlemmer fra både kommunal og statlig sektor. Difi får råd fra Standardiseringsrådet om hvilke standarder som bør være anbefalt eller obligatorisk i offentlig sektor.

Det foreliggende dokumentet er utarbeidet av en arbeidsgruppe ledet av Difi, i henhold til Standardiseringsrådets arbeidsmetodikk.

Standarden inngår i https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/referansekatalogen/begrepsanalyse-og-definisjonsarbeid[bruksområdet “Begrepsanalyse og definisjonsarbeid”] i _Referansekatalogen_. Denne versjonen skal erstatte den første versjonen fra mai 2012.

Se <<vedlegg B>> for de viktigste endringene fra versjon 1 til denne versjonen (versjon 2) av standarden.


== Formål, omfang og avgrensinger

Det er et uttrykt ønske, både__ __fra regjeringshold og fra offentlig sektor, at ulike deler av forvaltningen skal kunne gjenbruke hverandres informasjon (ofte data) i mye større grad enn i dag. Dette vil bl.a. spare både offentlig sektor og dens brukere for dobbeltarbeid knyttet til innsamling/avgiving av informasjon og vil hjelpe til å oppfylle “kun én gang”-prinsippet, dvs. samme informasjon (f.eks. sivilstand) skal bare samles inn ett sted i forvaltningen og så gjenbrukes av alle andre som har behov for og rettslig grunnlag til å bruke denne informasjonen.

For å identifisere hvilken informasjon som er aktuell til deling og gjenbruk er det imidlertid nødvendig å vite hva de ulike etatene legger i begrepene som er knyttet til data. For f.eks. å vite om en kan gjenbruke Skatteetatens data for lønn, må en vite om Skatteetaten definerer lønn på samme måte som ens egen etat. Dette betyr at offentlig sektor må definere og tilgjengeliggjøre sine begreper. Denne standarden skal sikre at begrepene forvaltet av offentlige virksomheter, beskrives på en felles, strukturert måte.

Standarden spesifiserer kun krav til innholdet i en begrepsbeskrivelse, ikke hvordan begrepsarbeidet generelt gjennomføres eller hvordan innholdet skal tilgjengeliggjøres elektronisk. Se ellers bruksområde “Begrepsanalyse og definisjonsarbeid” i https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/referansekatalogen[_Referansekatalogen]_ for andre aktuelle standarder og veiledere.

Denne versjonen av standarden fokuserer på informasjon som er nødvendig for å støtte deling** **av begrepsbeskrivelser. Virksomhetsinterne behov blir derfor ikke prioritert i foreliggende versjon.

== Normative referanser

Følgende referanser er normative og danner grunnlag for denne standarden:

* NS-ISO 704:2009 _Terminologiarbeid - Prinsipper og metoder_
* NS-ISO 1087:2000 _Terminologiarbeid - Ordliste - Del 1: Teori og anvendelser_
* _Termlosen_, som er en anbefalt forvaltningsstandard for begrepsanalyse og definisjonsarbeid
