
== Krav til innhold i beskrivelse av et begrep

Dette kapittelet beskriver hva som skal dokumenteres for at en begrepsbeskrivelse skal være i samsvar med standarden. Noe av informasjonen er obligatorisk, resten er valgfri. Blant den valgfrie informasjonen kan en velge å inkludere de delene en finner hensiktsmessig. Når den valgfrie informasjonen inkluderes, skal den følge standarden. Overordnet kan man si at standarden gir mulighet til å:

* dokumentere begrepets anbefalte term og eventuelle tillatte og frarådde termer
* dokumentere begrepets definisjon og eventuelle alternative formuleringer av samme definisjon
* beskrive eventuelle relasjoner begrepet måtte ha til andre begreper
* beskrive et begrep på flere språk
* knytte begrepet til en gruppering av begreper (begrepssamling, se <<kapittel 5>>)

I normativt <<vedlegg A>> til dette dokumentet er kravene også beskrevet i form av en http://www.uml.org/[UML]-modell.

Det er utarbeidet en informativ veileder for bruk av denne standarden. Veilederen inneholder mer utfyllende forklaring og eksempler på bruk av standarden. Se under https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/standarder/referansekatalogen/begrepsanalyse-og-definisjonsarbeid[bruksområdet Begrepsanalyse og definisjonsarbeid] i _Referansekatalogen_.

=== Obligatorisk informasjon

Når et begrep beskrives, skal følgende informasjon alltid tas med:


* *Anbefalt term*: En begrepsbeskrivelse skal alltid inneholde minst én <<anbefalt term>>, men maksimalt én per språk/målform.
** Språk/målform som termen er skrevet i, skal alltid oppgis.
* *Definisjon*: En begrepsbeskrivelse skal alltid inneholde minst én <<definisjon>>, men maksimalt én per språk/målform.
** Språk/målform som definisjonen er skrevet i, skal alltid oppgis.
* *Identifikator*: En begrepsbeskrivelse skal alltid inneholde en unik og varig identifikator til det aktuelle begrepet.
Ansvarlig virksomhet: En begrepsbeskrivelse skal alltid inneholde opplysninger om den ansvarlige virksomheten.


.Et informativt eksempel på en beskrivelse av et begrep, ved å bruke kun obligatorisk informasjon, der “(nb)” markerer at teksten er skrevet på bokmål.

|===
|*Anbefalt term*|heltidssysselsatt (nb)
|*Definisjon*|person som har en avtalt ukentlig arbeidstid på 37 timer og mer, samt personer med annen avtalt arbeidstid som oppgir at dette utgjør heltid. (nb)
|*Identifikator*|https://www.ssb.no/a/metadata/conceptvariable/vardok/1127/nb[https://www.ssb.no/a/metadata/conceptvariable/vardok/1127/nb]
|*Ansvarlig virksomhet*|971 526 920 (med organisasjonsnr, i henhold til standarden)
|===

=== Valgfri informasjon

I tillegg til obligatorisk informasjon som en alltid skal ta med i en begrepsbeskrivelse, kan følgende valgfri informasjon også tas med:

* Tillatt term: en eller flere <<tillatte termer>>.
** Når en tar med en tillatt term, skal språk/målform termen er skrevet i, oppgis.
* Frarådet term: en eller flere<<frarådede termer>>.
** Når en tar med en frarådet term, skal språk/målform termen er skrevet i, oppgis.
* Datastrukturterm: en eller flere termer som brukes i en datastruktur eller lignende (f.eks. navn for en klasse eller attributt i et UML-diagram, tagnavn i en XML-fil osv.)
* Alternativ formulering: en eller flere <<alternative formuleringer>> av definisjonen.
** Når en tar med en alternativ formulering, skal språk/målform den alternative formuleringen er skrevet i, oppgis.
* Merknad: en eller flere utdypende forklaringer til definisjon eller alternativ formulering.
** Når merknad tas med, skal språk/målform teksten er skrevet i, oppgis.
* Eksempel: et eller flere eksempler som eksemplifiserer begrepet.
** Når eksempel tas med, skal språk/målform teksten er skrevet i, oppgis.
* Omfang: lovlige kategorier eller verdiområder for et begrep.
** Eksempel på kategorier: _Standard for sivilstand_ spesifiserer hva som er lovlige kategorier for begrepet ‘sivilstand’, f.eks. ugift, gift og skilt.
** Eksempel på verdiområde: For begrepet ‘alder’__ __kan verdiområdet beskrives som “alle positive tall”.
* Fagområde: fagområde som begrepet har sitt opphav fra.
** Når fagområde tas med, skal språk/målform teksten er skrevet i, oppgis.
* Bruksområde: et eller flere anvendelsesområder der begrepet brukes i.
** Når bruksområde tas med, skal språk/målform teksten er skrevet i, oppgis.
* Beskrivelse av kilde til definisjon eller alternativ formulering:
** Kilde(r) til definisjon eller alternativ formulering kan oppgis når definisjonen eller den alternative formuleringen er hentet fra eller basert på en eller flere kilder.
** En kan også oppgi om en definisjon eller en alternativ formulering er: ‘sitat fra kilde’, ‘basert på kilde’, eller ‘egendefinert’. Se <<Kodeliste Forhold til kilde (ForholdTilKilde)>> for forklaring på lovlige verdier for ‘forhold til kilde’.
* Målgruppe: Til en ‘tillatt term’, ‘definisjon’ eller ‘alternativ formulering’, kan en oppgi målgruppen teksten er ment for. Valgmulighetene her er ‘allmennheten’ eller ‘fagspesialist’. Se <<Kodeliste Målgruppe (Målgruppe)>> for forklaring på lovlige verdier til ‘målgruppe’.
* Relasjoner til andre begreper: et begrep kan ha en eller flere relasjoner til andre begreper.
** Assosiative, generiske eller partitive relasjoner:
*** Til en gitt assosiativ relasjon skal det alltid tas med minst én beskrivelse, men maksimalt én per språk/målform.
*** Til en generisk eller partitiv relasjon kan man beskrive inndelingskriteriet, maksimalt én beskrivelse per språk/målform.
** ‘Se også’-relasjoner: Et gitt begrep kan ha ‘se også’-relasjon til et eller flere andre begreper.
** ‘Erstatter’-/‘erstattes av’-relasjoner:
*** Erstatter: et eller flere andre begreper som det aktuelle begrepet erstatter.
*** Erstattes av: et eller flere andre begreper som det aktuelle begrepet blir erstattet av.
*** Merknad: ‘erstatter’ / ‘erstattes av’ skal ikke brukes mellom versjoner av samme begrep (dvs. begrepsbeskrivelse som har samme identifikator).
* Gyldighetsperiode: Til et begrep kan en ta med tidsperioden beskrivelsen av begrepet er gyldig innenfor, som oppgis som ‘dato gyldig fra og med’ og/eller ‘dato gyldig til og med’.
* Sist oppdatert: En kan oppgi dato når en gitt beskrivelse er sist oppdatert. Dette gjelder: begrepsbeskrivelse i sin helhet, en ‘anbefalt term’, en ‘tillatt term’, en ‘frarådet term’, en ‘datastrukturterm’, en ‘definisjon’, en ‘alternativ formulering’, en assosiativ/generisk/partitiv relasjon til et annet begrep.
* Kontaktpunkt: En kan oppgi kontaktpunkt i den ansvarlige virksomhet.


.Et informativt eksempel som illustrerer bruk av flere felter fra standarden, der den obligatoriske informasjonen er *uthevet* og språkkode oppgitt i parentes (“(nn)” for norsk nynorsk).
|===

|*Anbefalt term*|husdyr (nn)
|*Definisjon*|dyr av ulike slag (pattedyr, fuglar, bier) som blir halde for nytteformål, til dømes for produksjon av produkt som mjølk, kjøt og ull, for al eller for trekkraft (nn)
|*Identifikator*|https://www.ssb.no/a/metadata/conceptvariable/vardok/1243/nn[https://www.ssb.no/a/metadata/conceptvariable/vardok/1243/nn]
|*Ansvarlig virksomhet*|971 526 920  (med organisasjonsnr, i henhold til standarden)
|Merknad|Kjæledyr blir ikkje rekna som husdyr (nn)
|Fagområde|jordbruk, jakt, viltstell (nn)
|Omfang|https://www.ssb.no/klass/klassifikasjoner/29[https://www.ssb.no/klass/klassifikasjoner/29]
|===
