
[[vedleggb, vedlegg B]]
== Vedlegg B (informativt) - Endringer fra versjon 1.0 til versjon 2.0

De viktigste endringene fra versjon 1 til denne versjonen (versjon 2.0) av standarden er som følger:

* Denne versjonen presiserer ved tittel at dette er en forvaltningsstandard.
* Denne versjonen av standarden prioriterer å støtte deling av begrepsbeskrivelser mellom virksomheter i norsk offentlig forvaltning. Virksomhetsinterne behov blir derfor ikke prioritert i denne versjonen.
* Denne versjonen skiller kun mellom obligatoriske og valgfrie felter, mens forrige versjon er inndelt i “obligatorisk del”, “utvidelse (anbefalt)”, “ytterligere utvidelser” samt “anbefalinger om forvaltningsdokumentasjon”.
* Denne versjonen dokumenterer innholdskravene i form av en http://www.uml.org/what-is-uml.htm[UML]-modell med kardinalitet/multiplisitet, noe som var savnet i forrige versjon.
* Denne versjonen inneholder færre obligatoriske krav til en begrepsbeskrivelse:
** ‘anbefalt term’
** ‘definisjon’
**  I tillegg to administrative beskrivelser: ‘identifikator’ og ‘ansvarlig virksomhet’
** Forrige versjon hadde i tillegg til forannevnte, også følgende i “obligatorisk del” (selv om flere av disse kravene er utformet som “dersom … ”):
*** ‘kilde’
*** ‘fagområde’
*** ‘gyldig fra’
*** ‘gyldig til’
*** ‘referanse til versjoner’
*** ‘klassifikasjon’
** Begge versjoner krever dokumentasjon av språk/målform.
* Denne versjonen stiller ikke eksplisitt innholdskrav til ‘referanse til versjoner’ som var i forrige versjon. Vi mener imidlertid at administrative beskrivelser som ‘gyldighetsperiode’ og ‘dato sist oppdatert’ vil danne et godt nok grunnlag for å ha denne type funksjonalitet i et IT-verktøy.
* Denne versjonen legger til rette for mer eksplisitt beskrivelse av relasjoner mellom begreper (i form av ‘assosiativ’, ‘generisk’, ‘partitiv’, ‘se også’, ‘erstatter’ og ‘erstattes av’-relasjoner), istedenfor ‘relaterte begreper’ i “utvidelse(anbefalt)” i forrige versjon.
* Denne versjonen har med flere valgfrie felter eksplisitt, hovedsakelig:
** ‘tillatt term’ og ‘frarådet term’, som var implisitt tatt med i “ytterligere utvidelser” i forrige versjon.
** ‘alternativ formulering’ (bl.a. med hensyn til “klarspråk”), ‘målgruppe’, ‘bruksområde’, ‘eksempel’, ‘datastrukturterm’.
* Noen navn er endret, f.eks. _omfang_ i denne versjonen istedenfor _klassifikasjon_ i forrige, _gyldig fra og med_ hhv. _gyldig til og med_ i denne versjonen istedenfor _gyldig fra_ hhv. _gyldig til_ i forrige.
* Denne versjonen spesifiserer også krav til begrepssamling som er valgfri.
