
= Normative referanser

Difi, DCAT-AP-NO, Standard for beskrivelse av datasett og datakataloger, 11.10.2016, https://doc.difi.no/dcat-ap-no/[https://doc.difi.no/dcat-ap-no/].

W3C Data on the Web Best Practices: Data Quality Vocabulary (DQV), footnote:[ DQV (Data Quality Vocabulary) er i skrivende stund ikke en anbefaling fra W3C ennå, men kun et “arbeidsgruppenotat”.] W3C Working Group Note 15 December 2016, https://www.w3.org/TR/vocab-dqv/[https://www.w3.org/TR/vocab-dqv/].

W3C Data on the Web Best Practices: Dataset Usage Vocabulary (DUV), footnote:[DUV (Dataset Usage Vocabulary) er i skrivende stund ikke en anbefaling fra W3C ennå, men kun et “arbeidsgruppenotat”.] W3C Working Group Note 15 December 2016, https://www.w3.org/TR/vocab-duv/[https://www.w3.org/TR/vocab-duv/].

W3C Simple Knowledge Organization System (SKOS), footnote:[EU har i “Commission Implementing Decision (EU) 2017/1358 of 20 July 2017” besluttet å kunne bruke SKOS i offentlige anskaffelser.  http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1500883656509&uri=CELEX:32017D1358] http://www.w3.org/2004/02/skos/[http://www.w3.org/2004/02/skos/].

W3C Web Annotation Data Model, W3C Recommendation 23 February 2017, https://www.w3.org/TR/annotation-model/.
